export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_USERNAME = 'UPDATE_USERNAME';
