export const RETRIEVE_ALBUMS = 'RETRIEVE_ALBUMS';
export const START_MENTION_SEARCH = 'START_MENTION_SEARCH';
export const STOP_MENTION_SEARCH = 'STOP_MENTION_SEARCH';
export const SUBMIT_WRITE = 'SUBMIT_WRITE';
export const UPDATE_ALBUM = 'UPDATE_ALBUM';
export const UPDATE_TITLE = 'UPDATE_TITLE';
export const UPDATE_EDITOR_STATE = 'UPDATE_EDITOR_STATE';
export const UPDATE_MENTION_SEARCH = 'UPDATE_MENTION_SEARCH';
