export const RETRIEVE_ALBUMS = 'RETRIEVE_ALBUMS';
export const SUBMIT_WRITE = 'SUBMIT_WRITE';
export const UPDATE_ALBUM = 'UPDATE_ALBUM';
export const UPDATE_TITLE = 'UPDATE_TITLE';

export const TOGGLE_BLOCK_TYPE = 'TOGGLE_BLOCK_TYPE';
export const TOGGLE_INLINE_STYLE = 'TOGGLE_INLINE_STYLE';
export const UPDATE_EDITOR_STATE = 'UPDATE_EDITOR_STATE';
export const UPLOAD_EDITOR_IMAGE_FILE = 'UPLOAD_EDITOR_IMAGE_FILE';
export const UPLOAD_EDITOR_IMAGE_FILE_SUCCESS = 'UPLOAD_EDITOR_IMAGE_FILE_SUCCESS';
export const UPLOAD_EDITOR_IMAGE_FILE_FAILURE = 'UPLOAD_EDITOR_IMAGE_FILE_FAILURE';

export const START_MENTION_SEARCH = 'START_MENTION_SEARCH';
export const UPDATE_MENTION_SEARCH = 'UPDATE_MENTION_SEARCH';
export const STOP_MENTION_SEARCH = 'STOP_MENTION_SEARCH';
